In [93]:
import os
from importlib import reload
from PIL import Image

import cambridge
reload(cambridge)

"""
dataset_root = '/Users/bj/Datasets/Cambridge/Street'
dataset = cambridge.CambridgeDataset(dataset_root, mode='train')
####
train_dataset = cambridge.CambridgeDataset(dataset_root, mode='train')
val_dataset = cambridge.CambridgeDataset(dataset_root, mode='val')
"""
import torch
train_dataset = [(torch.randn(3, 360, 480),torch.randn(3),torch.randn(4)) for i in range(10)]
val_dataset = [(torch.randn(3, 360, 480),torch.randn(3),torch.randn(4)) for i in range(2)]
#image, tr, rot = train_dataset[0]

In [94]:
import os
from importlib import reload
from PIL import Image

import torch
import torchvision

import models.posenet
reload(models.posenet)

model = models.posenet.PoseNet()

x = torch.randn(10, 3, 360, 480)

tr,rot = model(x)

In [67]:
tr,rot

(tensor([[ 0.0791, -0.0112,  0.1420],
         [-0.1028,  0.1703,  0.0259],
         [-0.0199,  0.1581,  0.1317],
         [ 0.0244,  0.1779,  0.0400],
         [ 0.0273,  0.0479, -0.1405],
         [ 0.0379,  0.0859,  0.0056],
         [ 0.1649,  0.0061,  0.0887],
         [ 0.0229,  0.0634,  0.1722],
         [ 0.1250, -0.0646,  0.0383],
         [ 0.1041,  0.2003,  0.1219]], grad_fn=<AddmmBackward0>),
 tensor([[-0.2104,  0.1113,  0.0529, -0.0982],
         [-0.0075,  0.1618, -0.1031, -0.1148],
         [ 0.0841,  0.3123,  0.0583,  0.0548],
         [ 0.0210,  0.1493,  0.0418, -0.0255],
         [-0.0935,  0.0451,  0.0585,  0.1022],
         [-0.0068,  0.1391, -0.0183, -0.0358],
         [-0.0666,  0.0802, -0.0587,  0.1371],
         [-0.0465,  0.4041,  0.1350,  0.0044],
         [ 0.0460,  0.2874,  0.0921, -0.0396],
         [ 0.1061,  0.2079, -0.0922,  0.0115]], grad_fn=<AddmmBackward0>))

In [5]:
x

tensor([[[[-0.5418, -0.2375, -0.1358,  ...,  0.9914,  0.9352, -0.3495],
          [ 1.9384,  0.4099,  0.7507,  ...,  0.6277, -0.0451, -0.3488],
          [-0.7644,  0.9143, -0.1277,  ..., -0.7396, -0.2824,  0.4619],
          ...,
          [ 0.1010, -0.2292,  1.2371,  ...,  1.6246, -0.4540,  0.0430],
          [ 1.2118, -0.1364,  2.0539,  ..., -1.0653,  1.0288,  0.6616],
          [-1.0820, -2.9813,  0.1470,  ...,  0.0650, -0.9436, -0.1391]],

         [[-1.0376, -2.1311, -1.3376,  ...,  0.1181, -1.1287, -1.5167],
          [ 0.2334, -1.1972,  0.4263,  ..., -0.6642,  0.3935, -0.0615],
          [ 1.6488,  0.3182, -0.2362,  ..., -0.3012,  0.4008, -1.5299],
          ...,
          [-2.0236, -0.9948,  0.2708,  ...,  0.8658, -0.8354,  0.8293],
          [-0.5659, -0.2764, -0.5439,  ..., -0.5758, -0.4536, -1.9036],
          [-0.4777, -0.2686, -0.7186,  ..., -0.9296,  0.7547,  0.0398]],

         [[-0.6656, -0.8544, -0.3061,  ...,  0.8734, -0.7764, -0.7126],
          [ 0.1069, -1.1959, -

In [103]:
import torch
from importlib import reload

import criterion
reload(criterion)

pred_tr = torch.randn(10, 3)
pred_rot = torch.randn(10, 4)

target_tr = torch.randn(10, 3)
target_rot = torch.randn(10, 4)

loss, tr_loss, rot_loss = criterion.compute_pose_loss(pred_tr, pred_rot, target_tr, target_rot)

In [96]:
# cuda or mps
if torch.cuda.is_available():
    device = torch.device('cuda')
#elif torch.backends.mps.is_available():
#    device = torch.device('mps')
else:
    device = torch.device('cpu')
print(f"Using {device} device")

Using cpu device


In [97]:
batch_size = 100
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size, shuffle=True)

In [53]:
for i, [x,tr,rot] in enumerate(train_loader):
    print(i)
    print(tr)
    print(rot)

0
tensor([[[ 1.2477, -0.3052,  0.4741]],

        [[-0.4763,  2.0261,  0.7082]],

        [[-0.6136,  0.6335,  1.3080]],

        [[-1.0743, -1.5516,  0.7213]],

        [[-0.4889, -1.7334, -1.2882]],

        [[ 0.6284, -0.9149, -0.1194]],

        [[ 2.1749, -1.5382,  1.2611]],

        [[ 0.5861,  0.4395,  0.4646]],

        [[ 0.5854, -0.6303,  1.2815]],

        [[-0.0473,  0.1853,  0.4024]],

        [[-0.1886,  0.1258, -0.7302]],

        [[-1.0708, -0.9722,  0.3135]],

        [[-2.1408,  2.6207,  0.3181]],

        [[ 1.6227, -0.6098,  0.2914]],

        [[-1.4813,  0.3056, -0.1031]],

        [[ 1.3099, -0.7312, -2.2128]],

        [[ 1.1224, -0.8602,  1.1124]],

        [[-0.1429, -1.8687,  0.2733]],

        [[ 1.0506, -1.2345,  0.4288]],

        [[-0.0598,  1.1306,  0.7396]],

        [[-0.8041, -1.1152,  0.5105]],

        [[ 0.4477, -0.5733, -1.6839]],

        [[-0.2867,  0.0647,  1.2229]],

        [[ 0.0961,  1.1496, -0.7716]],

        [[ 1.6630,  0.0262,  0.6736]],

In [98]:
# logger
class AverageMeter():
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count

In [99]:
learning_rate = 1e-5
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [29]:
for i, x in enumerate(train_loader):
    print(i)

0
1


In [87]:
x = torch.randn(10, 3, 360, 480)

tr,rot = model(x)

In [108]:
for i, [X, tr,rot] in enumerate(train_loader):
    X = X.to(device)
    print(X.size())
    print(tr.size())
    pred_tr, pred_rot = model(X)
    print(pred_tr.size())
    print(pred_rot.size())
    criterion(pred_tr, pred_rot, tr, rot)

torch.Size([10, 3, 360, 480])
torch.Size([10, 3])
torch.Size([10, 3])
torch.Size([10, 4])


TypeError: 'module' object is not callable

In [109]:
pred_tr = torch.randn(10, 3)
pred_rot = torch.randn(10, 4)

target_tr = torch.randn(10, 3)
target_rot = torch.randn(10, 4)
criterion(pred_tr, pred_rot, target_tr, target_rot)

TypeError: 'module' object is not callable

In [59]:
model(X[0])

(tensor([[0.0386, 0.0501, 0.0399]], grad_fn=<AddmmBackward0>),
 tensor([[ 0.0468, -0.0172,  0.0498,  0.1135]], grad_fn=<AddmmBackward0>))

In [110]:
num_epochs = 10
loss_meter = AverageMeter()

train_losses = []
val_losses = []

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):

    for param_group in optimizer.param_groups:
        print('learing rage: ', param_group['lr'])

    # train
    model.train()
    print ('------------------- Train: Epoch [{}/{}] -------------------'.format(\
        epoch+1, num_epochs) )

    loss_meter.reset()

    for i, [X, tr,rot] in enumerate(train_loader):
        X = X.to(device)
        tr = tr.to(device)
        rot = rot.to(device)

        # Forward pass
        pred_tr, pred_rot = model(X)
        loss, tr_loss, rot_loss = criterion.compute_pose_loss(pred_tr, pred_rot, tr, rot)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # logging
        loss_meter.update(loss.item(), X.size()[0] )

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(\
                epoch+1, num_epochs, i+1, total_step, loss_meter.avg) )

    print ('==> Train loss: {:.4f}'.format(loss_meter.avg) )
    train_losses.append(loss_meter.avg)

    # val
    model.eval()
    print ('------------------- Val.: Epoch [{}/{}] -------------------'.format(\
        epoch+1, num_epochs) )

    loss_meter.reset()

    for i, [X, tr,rot] in enumerate(val_loader):
        X = X.to(device)
        tr = tr.to(device)
        rot = rot.to(device)

        # Forward pass
        pred_tr, pred_rot = model(X)
        loss, tr_loss, rot_loss = criterion.compute_pose_loss(pred_tr, pred_rot, tr, rot)

        # logging
        loss_meter.update(loss.item(), X.size()[0] )

        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(\
                epoch+1, num_epochs, i+1, total_step, loss_meter.avg) )

    print ('==> Val. loss: {:.4f}'.format(loss_meter.avg) )
    val_losses.append(loss_meter.avg)

learing rage:  1e-05
------------------- Train: Epoch [1/10] -------------------
==> Train loss: 163.6833
------------------- Val.: Epoch [1/10] -------------------
==> Val. loss: 259.3043
learing rage:  1e-05
------------------- Train: Epoch [2/10] -------------------
==> Train loss: 34.3406
------------------- Val.: Epoch [2/10] -------------------
==> Val. loss: 237.6011
learing rage:  1e-05
------------------- Train: Epoch [3/10] -------------------
==> Train loss: 14.7382
------------------- Val.: Epoch [3/10] -------------------
==> Val. loss: 131.8996
learing rage:  1e-05
------------------- Train: Epoch [4/10] -------------------
==> Train loss: 7.8613
------------------- Val.: Epoch [4/10] -------------------
==> Val. loss: 152.7768
learing rage:  1e-05
------------------- Train: Epoch [5/10] -------------------
==> Train loss: 4.6380
------------------- Val.: Epoch [5/10] -------------------
==> Val. loss: 147.2695
learing rage:  1e-05
------------------- Train: Epoch [6/10] 

In [4]:
tr

tensor([[-0.0392, -0.0506, -0.0031]], grad_fn=<AddmmBackward0>)

In [5]:
rot

tensor([[ 0.0454, -0.0083,  0.0235,  0.0077]], grad_fn=<AddmmBackward0>)